In [1]:
import numpy as np
import pandas as pd

In [2]:
g = np.random.permutation(range(10))

In [3]:
for i in range(50):
    g = np.append(g, np.random.permutation(range(10)), axis=0)


In [4]:
len(g)

510

In [5]:
g

array([8, 2, 5, 7, 1, 4, 0, 6, 3, 9, 5, 0, 3, 2, 4, 9, 6, 7, 1, 8, 0, 7, 2,
       8, 9, 3, 1, 4, 5, 6, 9, 6, 0, 1, 7, 3, 4, 5, 8, 2, 3, 0, 5, 9, 4, 6,
       1, 8, 2, 7, 3, 2, 1, 0, 9, 4, 8, 5, 6, 7, 2, 9, 7, 0, 6, 4, 8, 3, 1,
       5, 5, 3, 9, 2, 8, 7, 6, 1, 4, 0, 8, 7, 0, 5, 9, 6, 2, 3, 1, 4, 4, 8,
       6, 3, 9, 0, 2, 1, 5, 7, 8, 5, 0, 4, 2, 6, 7, 1, 3, 9, 3, 1, 8, 9, 4,
       2, 6, 0, 7, 5, 1, 7, 2, 6, 9, 0, 4, 3, 5, 8, 5, 7, 6, 4, 9, 2, 3, 0,
       8, 1, 3, 0, 5, 8, 2, 1, 9, 6, 4, 7, 3, 9, 7, 6, 5, 2, 4, 8, 1, 0, 0,
       1, 8, 5, 2, 9, 7, 6, 4, 3, 8, 2, 9, 1, 5, 6, 4, 0, 7, 3, 0, 3, 4, 1,
       6, 8, 5, 2, 9, 7, 3, 4, 7, 5, 1, 2, 8, 9, 6, 0, 5, 4, 0, 2, 6, 7, 8,
       1, 9, 3, 9, 1, 2, 6, 3, 5, 4, 7, 8, 0, 7, 9, 3, 2, 0, 1, 6, 8, 4, 5,
       5, 1, 0, 7, 6, 4, 8, 2, 3, 9, 9, 1, 2, 8, 4, 3, 7, 6, 0, 5, 2, 3, 8,
       4, 7, 0, 9, 5, 6, 1, 4, 0, 1, 3, 7, 8, 9, 6, 2, 5, 4, 7, 2, 9, 0, 3,
       5, 1, 8, 6, 5, 1, 3, 2, 7, 6, 0, 9, 4, 8, 9, 4, 2, 7, 3, 0, 1, 8, 5,
       6, 0,

In [6]:
g.reshape(51, 10)

array([[8, 2, 5, 7, 1, 4, 0, 6, 3, 9],
       [5, 0, 3, 2, 4, 9, 6, 7, 1, 8],
       [0, 7, 2, 8, 9, 3, 1, 4, 5, 6],
       [9, 6, 0, 1, 7, 3, 4, 5, 8, 2],
       [3, 0, 5, 9, 4, 6, 1, 8, 2, 7],
       [3, 2, 1, 0, 9, 4, 8, 5, 6, 7],
       [2, 9, 7, 0, 6, 4, 8, 3, 1, 5],
       [5, 3, 9, 2, 8, 7, 6, 1, 4, 0],
       [8, 7, 0, 5, 9, 6, 2, 3, 1, 4],
       [4, 8, 6, 3, 9, 0, 2, 1, 5, 7],
       [8, 5, 0, 4, 2, 6, 7, 1, 3, 9],
       [3, 1, 8, 9, 4, 2, 6, 0, 7, 5],
       [1, 7, 2, 6, 9, 0, 4, 3, 5, 8],
       [5, 7, 6, 4, 9, 2, 3, 0, 8, 1],
       [3, 0, 5, 8, 2, 1, 9, 6, 4, 7],
       [3, 9, 7, 6, 5, 2, 4, 8, 1, 0],
       [0, 1, 8, 5, 2, 9, 7, 6, 4, 3],
       [8, 2, 9, 1, 5, 6, 4, 0, 7, 3],
       [0, 3, 4, 1, 6, 8, 5, 2, 9, 7],
       [3, 4, 7, 5, 1, 2, 8, 9, 6, 0],
       [5, 4, 0, 2, 6, 7, 8, 1, 9, 3],
       [9, 1, 2, 6, 3, 5, 4, 7, 8, 0],
       [7, 9, 3, 2, 0, 1, 6, 8, 4, 5],
       [5, 1, 0, 7, 6, 4, 8, 2, 3, 9],
       [9, 1, 2, 8, 4, 3, 7, 6, 0, 5],
       [2, 3, 8, 4, 7, 0,

In [7]:
def factorial(n):
    r = 1
    for i in range(1, n+1):
        r *= i
    return r
        

In [8]:
factorial(10)

3628800

In [9]:
def random_index(n, depth=30):
    depth = factorial(n) * depth
    g = np.random.permutation(range(n))
    for i in range(depth-1):
        g = np.append(g, np.random.permutation(range(n)))
    return g.reshape((depth, n))

In [10]:
random_index(5)

array([[1, 2, 0, 3, 4],
       [3, 0, 1, 4, 2],
       [3, 2, 4, 0, 1],
       ..., 
       [4, 0, 2, 1, 3],
       [3, 0, 1, 4, 2],
       [0, 3, 1, 4, 2]])

In [11]:
x = pd.DataFrame(random_index(5))

In [12]:
len(x)

3600

In [13]:
alist = [3, 29, 675, 4932, 5]

In [14]:
def random_elements(alist, depth = 30):
    depth = factorial(len(alist)) * 30
    g = np.random.permutation(alist)
    for i in range(depth - 1):
        g = np.append(g, np.random.permutation(alist), axis = 0)
    return g.reshape((depth, len(alist)))
        
    

In [15]:
r = random_elements(alist)

In [16]:
len(r)

3600

In [17]:
r = pd.DataFrame(r)

In [18]:
r

0     1     2     3     4
0      675    29  4932     5     3
1      675     3    29     5  4932
2        3     5   675  4932    29
3      675  4932     3    29     5
4       29     3  4932   675     5
5     4932   675    29     3     5
6        3     5    29  4932   675
7     4932     5    29     3   675
8      675     3    29  4932     5
9        3    29  4932     5   675
10    4932    29     5   675     3
11       3  4932     5   675    29
12    4932   675    29     3     5
13     675  4932     3     5    29
14      29   675     5     3  4932
15       5  4932     3    29   675
16     675    29     5     3  4932
17    4932     5    29   675     3
18       5   675  4932    29     3
19    4932   675    29     3     5
20      29     5   675     3  4932
21       3   675    29  4932     5
22       3  4932     5    29   675
23    4932     3     5    29   675
24    4932    29   675     3     5
25      29     3  4932     5   675
26     675     3     5    29  4932
27    4932     5    29     3   675
28     675     5    29  4932     3
29     675     5     3    29  4932
...    ...   ...   ...   ...   ...
3570   675    29     3  4932     5
3571     5    29   675     3  4932
3572  4932     5     3   675    29
3573   675  4932     3     5    29
3574   675     3     5  4932    29
3575   675    29  4932     5     3
3576    29   675  4932     5     3
3577  4932     5   675     3    29
3578     3     5   675    29  4932
3579   675     3     5    29  4932
3580  4932     3    29     5   675
3581  4932     5     3   675    29
3582   675    29  4932     3     5
3583     3   675     5    29  4932
3584  4932     5     3    29   675
3585     3    29   675     5  4932
3586     3    29  4932     5   675
3587     5  4932     3    29   675
3588     5  4932    29     3   675
3589  4932     3     5   675    29
3590    29     3  4932   675     5
3591  4932     5    29     3   675
3592  4932     3    29     5   675
3593     5    29   675  4932     3
3594  4932     5   675     3    29
3595   675     3     5    29  4932
3596     5    29  4932     3   675
3597    29     5     3  4932   675
3598   675     5    29     3  4932
3599  4932    29     3     5   675

[3600 rows x 5 columns]

In [19]:
def join_num(alist):
    temp = [str(i) for i in alist]
    return ''.join(temp)

In [20]:
join_num([1, 3, 7, 9, 54])

'137954'

In [21]:
data = r.apply(join_num, axis = 1)

In [22]:
data

0       67529493253
1       67532954932
2       35675493229
3       67549323295
4       29349326755
5       49326752935
6       35294932675
7       49325293675
8       67532949325
9       32949325675
10      49322956753
11      34932567529
12      49326752935
13      67549323529
14      29675534932
15      54932329675
16      67529534932
17      49325296753
18      56754932293
19      49326752935
20      29567534932
21      36752949325
22      34932529675
23      49323529675
24      49322967535
25      29349325675
26      67535294932
27      49325293675
28      67552949323
29      67553294932
           ...     
3570    67529349325
3571    52967534932
3572    49325367529
3573    67549323529
3574    67535493229
3575    67529493253
3576    29675493253
3577    49325675329
3578    35675294932
3579    67535294932
3580    49323295675
3581    49325367529
3582    67529493235
3583    36755294932
3584    49325329675
3585    32967554932
3586    32949325675
3587    54932329675
3588    54932293675


In [23]:
len(data.unique())

120

In [24]:
data.max()

'67554932329'

In [25]:
data.min()

'29349325675'

In [26]:
data.value_counts()

34932529675    49
49325293675    45
35493229675    43
49326752935    43
54932675329    40
54932293675    38
36752949325    38
67529493235    38
54932329675    38
35675493229    38
32954932675    37
67529349325    37
49322936755    36
67549322935    36
52967549323    36
29493267553    36
35296754932    35
29493236755    35
67549323529    35
36754932529    35
32956754932    35
49326752953    35
29349326755    35
49326753295    35
29675534932    34
67529493253    34
67552934932    34
67535294932    34
53294932675    34
49323567529    34
               ..
29675549323    26
67532949325    26
36752954932    26
54932296753    26
49325329675    26
49323295675    25
54932367529    25
49326755329    25
29356754932    25
32967554932    25
29534932675    25
34932675529    25
56753294932    24
56754932293    24
29367554932    24
53493267529    24
32949326755    24
29549323675    23
35493267529    22
67534932295    22
67549322953    22
52936754932    22
29675493235    21
34932675295    21
2949323567

这个方法依然效率低下，当数组中元素个数超过 6 就运算非常缓慢，不可用了。